version: "3.9"
services:
  account-spaces-db:
    image: postgres:15.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=spaces
      - POSTGRES_PASSWORD=spaces
      - POSTGRES_DB=account_spaces
    ports:
      - '5432:5432'
    volumes:
      - account-spaces-db-data:/var/lib/postgresql/data
    networks:
      - account-spaces-network

volumes:
  account-spaces-db-data:

networks:
  account-spaces-network: